spring.application.name=login-app

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/login_app_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:NeymarLM10$}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}

server.port=${PORT:8080}

app.jwt.secret=${APP_JWT_SECRET:change_this_to_a_long_random_secret_key_minimum_32_characters}
app.jwt.expiration-ms=86400000
